language: php

php:
  - 5.6
  - 7.0

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: 16efa6c23c2e8c705826b0e66778fbe7
  ADMIN_EMAIL: admin@medlib.fr
  ADMIN_NAME: Admin
  ADMIN_PASSWORD: SoSecurEvinr0rd
  BROADCAST_DRIVER: log

## Cache composer bits
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
  - vendor
    
branches:
  - master
  - develop

# Setting up pre-requirements
before_install:
  - git clone git://github.com/medlib-v2/test-unit.git tests

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit
  - npm test
