language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

## Cache composer directories
cache:
  directories:
    - node_modules # NPM packages
    - vendor
    
branches:
  - master
  - develop

#Start MySQL
sudo: required
services:
  - mysql

# Setting up pre-requirements
before_install:
  - git clone git://github.com/medlib-v2/test-unit.git tests
  - cp .env.travis .env
  - rm -rf .env.testing
  - mysql -e 'create database if not exists medlib_test;'
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - npm i maildev
  - travis_retry composer self-update
  - travis_retry node_modules/maildev/bin/maildev 1&2>/dev/null

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  #- npm install
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-scripts --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-scripts --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-scripts --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - php artisan migrate
  - php artisan db:seed

script:
  - phpunit
  - npm test


matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true

