<template lang="html">
    <input class="form-control" :class="type" type="text" ref="complete" v-model="address" @focus="geolocate()" :placeholder="placeholder">
</template>

<script type="text/babel">
import Store from '../stores'

export default {
    name: 'google-autocomplete',
    props: ['type', 'placeholder'],
    data() {
        return {
            /**
             * input bound to autocomplete.
             */
            'address': '',
            /**
             * google autocomplete object.
             */
            'autocomplete': '',
            /**
             * google inputs retrieved.
             */
            'inputs': {
                route: 'long_name',
                country: 'long_name',
                administrative_area_level_1: 'long_name',
                locality: 'long_name',
                postal_code: 'short_name'
            },
            /** API info. **/
            api: {
                /** URL on charge to retrieve addresses from the google places API. **/
                domain: 'https://maps.googleapis.com/maps/api/js',
                /** This key is generated by google console API manager. You will have to register your API project on
                 * https://console.developers.google.com, then you will be able to use this component within your
                 * own project. **/
                key: window.GOOGLE_AUTOCOMPLETE_KEY,
                /** Register the google places API library. **/
                libraries: 'places'
            }
        }
    },
    mounted() {
        window.onload = this.loadScript( this.api.domain + '?key=' + this.api.key + '&libraries=' + this.api.libraries, this.bindAutocomplete )
    },
    watch: {
        /**
         * Store the address retrieved in the vuex store.
         *
         * @return {Void}
         */
        address() {
            Store.commit('SET_ADDRESS', this.address)
        }
    },
    methods: {
        /**
         * Load google class for a given library.
         *
         * @param  src
         * @param  callback
         * @return {Void}
         */
        loadScript(src, callback) {
            let script = document.createElement("script")
            document.body.appendChild(script)
            if (callback)
                script.onload = callback
            script.src = src
        },
        /**
         * Bind autocomplete to its property.
         *
         * @return {Void}
         */
        bindAutocomplete () {
            this.autocomplete = new google.maps.places.Autocomplete(this.$refs.complete, { types: ['geocode'] } )
            this.autocomplete.addListener('place_changed', this.pipeAddress)
        },
        /**
         * Look up places and emit an event.
         *
         * @return {Void}
         */
        pipeAddress () {
            let data  = {}
            let place = this.autocomplete.getPlace()
            if (place.address_components !== undefined) {
                for (let i = 0; i < place.address_components.length; i++) {
                    let input = place.address_components[i].types[0]
                    if (this.inputs[input]) {
                        data[input] = place.address_components[i][this.inputs[input]]
                    }
                }
                data = JSON.stringify(data)
                Store.commit('SET_ADDRESS', JSON.parse(data))
            }
        },
        /**
         * Get the user location.
         *
         * @return {Void}
         */
        geolocate() {
            if (navigator.geolocation) {
                let vm = this
                navigator.geolocation.getCurrentPosition((position) => {
                    let geolocation = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    }
                    let circle = new google.maps.Circle({
                        center: geolocation,
                        radius: position.coords.accuracy
                    })
                    vm.autocomplete.setBounds(circle.getBounds())
                })
            }
        }
    }
}
</script>
