<div class="col-sm-8">
    <label for="multiple-select">Place of Publication</label>
    <br>
    <div class="select2-container select2-container-multi select2 form-control" id="s2id_multiple-select">
    </div>
    <select multiple="" data-placeholder="Select to limit by place" name="place" data-minimum-results-for-search="5" tabindex="-1" class="select2 form-control select2-offscreen" id="multiple-select" title="Select to limit by place">
        <option selected="selected" value="all">All Places</option>
        <option value="United States">United States</option>
        <option value="United Kingdom">United Kingdom</option>
        <option value="af">Afghanistan</option>
        <option value="alu">Alabama</option>
        <option value="aku">Alaska</option>
        <option value="aa">Albania</option>
        <option value="abc">Alberta</option>
        <option value="ae">Algeria</option>
        <option value="as">American Samoa</option>
        <option value="an">Andorra</option>
        <option value="ao">Angola</option>
        <option value="am">Anguilla</option>
        <option value="ay">Antarctica</option>
        <option value="aq">Antigua and Barbuda</option>
        <option value="ag">Argentina</option>
        <option value="azu">Arizona</option>
        <option value="aru">Arkansas</option>
        <option value="ai">Armenia (Republic)</option>
        <option value="aw">Aruba</option>
        <option value="at">Australia</option>
        <option value="aca">Australian Capital Territory</option>
        <option value="au">Austria</option>
        <option value="aj">Azerbaijan</option>
        <option value="bf">Bahamas</option>
        <option value="ba">Bahrain</option>
        <option value="bg">Bangladesh</option>
        <option value="bb">Barbados</option>
        <option value="bw">Belarus</option>
        <option value="be">Belgium</option>
        <option value="bh">Belize</option>
        <option value="dm">Benin</option>
        <option value="bm">Bermuda Islands</option>
        <option value="bt">Bhutan</option>
        <option value="bo">Bolivia</option>
        <option value="bn">Bosnia and Hercegovina</option>
        <option value="bs">Botswana</option>
        <option value="bv">Bouvet Island</option>
        <option value="bl">Brazil</option>
        <option value="bcc">British Columbia</option>
        <option value="bi">British Indian Ocean Territory</option>
        <option value="vb">British Virgin Islands</option>
        <option value="bx">Brunei</option>
        <option value="bu">Bulgaria</option>
        <option value="uv">Burkina Faso</option>
        <option value="br">Burma</option>
        <option value="bd">Burundi</option>
        <option value="cau">California</option>
        <option value="cb">Cambodia</option>
        <option value="cm">Cameroon</option>
        <option value="xxc">Canada (province unidentified) [current]</option>
        <option value="cn">Canada (province unidentified) [used before 1988]</option>
        <option value="cv">Cape Verde</option>
        <option value="ca">Caribbean Netherlands</option>
        <option value="cj">Cayman Islands</option>
        <option value="cx">Central African Republic</option>
        <option value="cd">Chad</option>
        <option value="cl">Chile</option>
        <option value="cc">China</option>
        <option value="ch">China (Republic : 1949- )</option>
        <option value="xa">Christmas Island (Indian Ocean)</option>
        <option value="xb">Cocos (Keeling) Islands</option>
        <option value="ck">Colombia</option>
        <option value="cou">Colorado</option>
        <option value="cq">Comoros</option>
        <option value="cf">Congo (Brazzaville)</option>
        <option value="cg">Congo, The Democratic Republic of The</option>
        <option value="ctu">Connecticut</option>
        <option value="cw">Cook Islands</option>
        <option value="xga">Coral Sea Islands Territory</option>
        <option value="cr">Costa Rica</option>
        <option value="iv">Cote d'Ivoire</option>
        <option value="ci">Croatia</option>
        <option value="cu">Cuba</option>
        <option value="co">Curacao</option>
        <option value="cy">Cyprus</option>
        <option value="xr">Czech Republic</option>
        <option value="cs">Czechoslovakia [used before 1993] -- see also: Czech Republic or Slovakia</option>
        <option value="deu">Delaware</option>
        <option value="dk">Denmark</option>
        <option value="dcu">District of Columbia</option>
        <option value="ft">Djibouti</option>
        <option value="dq">Dominica</option>
        <option value="dr">Dominican Republic</option>
        <option value="ec">Ecuador</option>
        <option value="ua">Egypt</option>
        <option value="es">El Salvador</option>
        <option value="enk">England</option>
        <option value="eg">Equatorial Guinea</option>
        <option value="ea">Eritrea</option>
        <option value="er">Estonia</option>
        <option value="et">Ethiopia</option>
        <option value="fk">Falkland Islands (Malvinas)</option>
        <option value="fa">Faroe Islands</option>
        <option value="fj">Fiji</option>
        <option value="fi">Finland</option>
        <option value="flu">Florida</option>
        <option value="fr">France</option>
        <option value="fg">French Guiana</option>
        <option value="fp">French Polynesia</option>
        <option value="go">Gabon</option>
        <option value="gm">Gambia</option>
        <option value="gz">Gaza Strip</option>
        <option value="gau">Georgia</option>
        <option value="gs">Georgia (Republic)</option>
        <option value="gw">Germany</option>
        <option value="ge">Germany (East) [used before 1991] -- see also: Germany</option>
        <option value="gh">Ghana</option>
        <option value="gi">Gibraltar</option>
        <option value="gr">Greece</option>
        <option value="gl">Greenland</option>
        <option value="gd">Grenada</option>
        <option value="gp">Guadeloupe</option>
        <option value="gu">Guam</option>
        <option value="gt">Guatemala</option>
        <option value="gv">Guinea</option>
        <option value="pg">Guinea-Bissau</option>
        <option value="gy">Guyana</option>
        <option value="ht">Haiti</option>
        <option value="hiu">Hawaii</option>
        <option value="hm">Heard and McDonald Islands</option>
        <option value="ho">Honduras</option>
        <option value="hu">Hungary</option>
        <option value="ic">Iceland</option>
        <option value="idu">Idaho</option>




        <option value="Hong Kong">Hong Kong</option>


        <option value="India">India</option>
        <option value="Indonesia">Indonesia</option>
        <option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
        <option value="Iraq">Iraq</option>
        <option value="Ireland">Ireland</option>
        <option value="Israel">Israel</option>
        <option value="Italy">Italy</option>
        <option value="Jamaica">Jamaica</option>
        <option value="Japan">Japan</option>
        <option value="Jordan">Jordan</option>
        <option value="Kazakhstan">Kazakhstan</option>
        <option value="Kenya">Kenya</option>
        <option value="Kiribati">Kiribati</option>
        <option value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
        <option value="Korea, Republic of">Korea, Republic of</option>
        <option value="Kuwait">Kuwait</option>
        <option value="Kyrgyzstan">Kyrgyzstan</option>
        <option value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
        <option value="Latvia">Latvia</option>
        <option value="Lebanon">Lebanon</option>
        <option value="Lesotho">Lesotho</option>
        <option value="Liberia">Liberia</option>
        <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
        <option value="Liechtenstein">Liechtenstein</option>
        <option value="Lithuania">Lithuania</option>
        <option value="Luxembourg">Luxembourg</option>
        <option value="Macao">Macao</option>
        <option value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
        <option value="Madagascar">Madagascar</option>
        <option value="Malawi">Malawi</option>
        <option value="Malaysia">Malaysia</option>
        <option value="Maldives">Maldives</option>
        <option value="Mali">Mali</option>
        <option value="Malta">Malta</option>
        <option value="Marshall Islands">Marshall Islands</option>
        <option value="Martinique">Martinique</option>
        <option value="Mauritania">Mauritania</option>
        <option value="Mauritius">Mauritius</option>
        <option value="Mayotte">Mayotte</option>
        <option value="Mexico">Mexico</option>
        <option value="Micronesia, Federated States of">Micronesia, Federated States of</option>
        <option value="Moldova, Republic of">Moldova, Republic of</option>
        <option value="Monaco">Monaco</option>
        <option value="Mongolia">Mongolia</option>
        <option value="Montenegro">Montenegro</option>
        <option value="Montserrat">Montserrat</option>
        <option value="Morocco">Morocco</option>
        <option value="Mozambique">Mozambique</option>
        <option value="Myanmar">Myanmar</option>
        <option value="Namibia">Namibia</option>
        <option value="Nauru">Nauru</option>
        <option value="Nepal">Nepal</option>
        <option value="Netherlands">Netherlands</option>
        <option value="Netherlands Antilles">Netherlands Antilles</option>
        <option value="New Caledonia">New Caledonia</option>
        <option value="New Zealand">New Zealand</option>
        <option value="Nicaragua">Nicaragua</option>
        <option value="Niger">Niger</option>
        <option value="Nigeria">Nigeria</option>
        <option value="Niue">Niue</option>
        <option value="Norfolk Island">Norfolk Island</option>
        <option value="Northern Mariana Islands">Northern Mariana Islands</option>
        <option value="Norway">Norway</option>
        <option value="Oman">Oman</option>
        <option value="Pakistan">Pakistan</option>
        <option value="Palau">Palau</option>
        <option value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
        <option value="Panama">Panama</option>
        <option value="Papua New Guinea">Papua New Guinea</option>
        <option value="Paraguay">Paraguay</option>
        <option value="Peru">Peru</option>
        <option value="Philippines">Philippines</option>
        <option value="Pitcairn">Pitcairn</option>
        <option value="Poland">Poland</option>
        <option value="Portugal">Portugal</option>
        <option value="Puerto Rico">Puerto Rico</option>
        <option value="Qatar">Qatar</option>
        <option value="Reunion">Reunion</option>
        <option value="Romania">Romania</option>
        <option value="Russian Federation">Russian Federation</option>
        <option value="Rwanda">Rwanda</option>
        <option value="Saint Helena">Saint Helena</option>
        <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
        <option value="Saint Lucia">Saint Lucia</option>
        <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
        <option value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
        <option value="Samoa">Samoa</option>
        <option value="San Marino">San Marino</option>
        <option value="Sao Tome and Principe">Sao Tome and Principe</option>
        <option value="Saudi Arabia">Saudi Arabia</option>
        <option value="Senegal">Senegal</option>
        <option value="Serbia">Serbia</option>
        <option value="Seychelles">Seychelles</option>
        <option value="Sierra Leone">Sierra Leone</option>
        <option value="Singapore">Singapore</option>
        <option value="Slovakia">Slovakia</option>
        <option value="Slovenia">Slovenia</option>
        <option value="Solomon Islands">Solomon Islands</option>
        <option value="Somalia">Somalia</option>
        <option value="South Africa">South Africa</option>
        <option value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
        <option value="South Sudan">South Sudan</option>
        <option value="Spain">Spain</option>
        <option value="Sri Lanka">Sri Lanka</option>
        <option value="Sudan">Sudan</option>
        <option value="Suriname">Suriname</option>
        <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
        <option value="Swaziland">Swaziland</option>
        <option value="Sweden">Sweden</option>
        <option value="Switzerland">Switzerland</option>
        <option value="Syrian Arab Republic">Syrian Arab Republic</option>
        <option value="Taiwan, Republic of China">Taiwan, Republic of China</option>
        <option value="Tajikistan">Tajikistan</option>
        <option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
        <option value="Thailand">Thailand</option>
        <option value="Timor-leste">Timor-leste</option>
        <option value="Togo">Togo</option>
        <option value="Tokelau">Tokelau</option>
        <option value="Tonga">Tonga</option>
        <option value="Trinidad and Tobago">Trinidad and Tobago</option>
        <option value="Tunisia">Tunisia</option>
        <option value="Turkey">Turkey</option>
        <option value="Turkmenistan">Turkmenistan</option>
        <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
        <option value="Tuvalu">Tuvalu</option>
        <option value="Uganda">Uganda</option>
        <option value="Ukraine">Ukraine</option>
        <option value="United Arab Emirates">United Arab Emirates</option>
        <option value="United Kingdom">United Kingdom</option>
        <option value="United States">United States</option>
        <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
        <option value="Uruguay">Uruguay</option>
        <option value="Uzbekistan">Uzbekistan</option>
        <option value="Vanuatu">Vanuatu</option>
        <option value="Venezuela">Venezuela</option>
        <option value="Viet Nam">Viet Nam</option>
        <option value="Virgin Islands, British">Virgin Islands, British</option>
        <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
        <option value="Wallis and Futuna">Wallis and Futuna</option>
        <option value="Western Sahara">Western Sahara</option>
        <option value="Yemen">Yemen</option>
        <option value="Zambia">Zambia</option>
        <option value="Zimbabwe">Zimbabwe</option>
    </select>
</div>
<div class="limitDiv">
    <br>
    <select title="Select to limit by place" name="place" id="place" size="5" multiple="">
        <option value="ilu">Illinois</option>
        <option value="ii">India</option>
        <option value="inu">Indiana</option><option value="io">Indonesia</option><option value="iau">Iowa</option><option value="ir">Iran</option><option value="iq">Iraq</option><option value="iy">Iraq-Saudi Arabia Neutral Zone</option><option value="ie">Ireland</option><option value="is">Israel</option><option value="it">Italy</option><option value="jm">Jamaica</option><option value="ja">Japan</option><option value="ji">Johnston Atoll</option><option value="jo">Jordan</option><option value="ksu">Kansas</option><option value="kz">Kazakhstan</option><option value="kyu">Kentucky</option><option value="ke">Kenya</option><option value="gb">Kiribati</option><option value="kn">Korea (North)</option><option value="ko">Korea (South)</option><option value="kv">Kosovo</option><option value="ku">Kuwait</option><option value="kg">Kyrgyzstan</option><option value="ls">Laos</option><option value="lv">Latvia</option><option value="le">Lebanon</option><option value="lo">Lesotho</option><option value="lb">Liberia</option><option value="ly">Libya</option><option value="lh">Liechtenstein</option><option value="li">Lithuania</option><option value="lau">Louisiana</option><option value="lu">Luxembourg</option><option value="xn">Macedonia</option><option value="mg">Madagascar</option><option value="meu">Maine</option><option value="mw">Malawi</option><option value="my">Malaysia</option><option value="xc">Maldives</option><option value="ml">Mali</option><option value="mm">Malta</option><option value="mbc">Manitoba</option><option value="xe">Marshall Islands</option><option value="mq">Martinique</option><option value="mdu">Maryland</option><option value="mau">Massachusetts</option><option value="mu">Mauritania</option><option value="mf">Mauritius</option><option value="ot">Mayotte</option><option value="mx">Mexico</option><option value="miu">Michigan</option><option value="fm">Micronesia (Federated States)</option><option value="xf">Midway Islands</option><option value="mnu">Minnesota</option><option value="msu">Mississippi</option><option value="mou">Missouri</option><option value="mv">Moldova</option><option value="mc">Monaco</option><option value="mp">Mongolia</option><option value="mtu">Montana</option><option value="mo">Montenegro</option><option value="mj">Montserrat</option><option value="mr">Morocco</option><option value="mz">Mozambique</option><option value="sx">Namibia</option><option value="nu">Nauru</option><option value="nbu">Nebraska</option><option value="np">Nepal</option><option value="ne">Netherlands</option><option value="na">Netherlands Antilles</option><option value="nvu">Nevada</option><option value="nkc">New Brunswick</option><option value="nl">New Caledonia</option><option value="nhu">New Hampshire</option><option value="nju">New Jersey</option><option value="nmu">New Mexico</option><option value="xna">New South Wales</option><option value="nyu">New York (State)</option><option value="nz">New Zealand</option><option value="nfc">Newfoundland and Labrador</option><option value="nq">Nicaragua</option><option value="ng">Niger</option><option value="nr">Nigeria</option><option value="xh">Niue</option><option value="nx">Norfolk Island</option><option value="ncu">North Carolina</option><option value="ndu">North Dakota</option><option value="nik">Northern Ireland</option><option value="nw">Northern Mariana Islands</option><option value="xoa">Northern Territory</option><option value="ntc">Northwest Territories</option><option value="no">Norway</option><option value="nsc">Nova Scotia</option><option value="nuc">Nunavut</option><option value="ohu">Ohio</option><option value="oku">Oklahoma</option><option value="mk">Oman</option><option value="onc">Ontario</option><option value="oru">Oregon</option><option value="pk">Pakistan</option><option value="pw">Palau</option><option value="pn">Panama</option><option value="pp">Papua New Guinea</option><option value="pf">Paracel Islands</option><option value="py">Paraguay</option><option value="pau">Pennsylvania</option><option value="pe">Peru</option><option value="ph">Philippines</option><option value="pc">Pitcairn Island</option><option value="pl">Poland</option><option value="po">Portugal</option><option value="pic">Prince Edward Island</option><option value="pr">Puerto Rico</option><option value="qa">Qatar</option><option value="quc">Qu├йbec (Province)</option><option value="qea">Queensland</option><option value="re">R├йunion</option><option value="riu">Rhode Island</option><option value="rm">Romania</option><option value="ru">Russia (Federation)</option><option value="rw">Rwanda</option><option value="sc">Saint-Barthelemy</option><option value="xj">Saint Helena</option><option value="xd">Saint Kitts-Nevis</option><option value="xk">Saint Lucia</option><option value="st">Saint-Martin</option><option value="xl">Saint Pierre and Miquelon</option><option value="xm">Saint Vincent and the Grenadines</option><option value="ws">Samoa</option><option value="sm">San Marino</option><option value="sf">Sao Tome and Principe</option><option value="snc">Saskatchewan</option><option value="su">Saudi Arabia</option><option value="stk">Scotland</option><option value="sg">Senegal</option><option value="rb">Serbia</option><option value="yu">Serbia and Montenegro [used before 2008]</option><option value="xxx"> -- see also: Kosovo, Montenegro, or Serbia</option><option value="se">Seychelles</option><option value="sl">Sierra Leone</option><option value="si">Singapore</option><option value="sn">Sint Maaarten</option><option value="xo">Slovakia</option><option value="xv">Slovenia</option><option value="bp">Solomon Islands</option><option value="so">Somalia</option><option value="sa">South Africa</option><option value="xra">South Australia</option><option value="scu">South Carolina</option><option value="sdu">South Dakota</option><option value="xs">South Georgia and the South Sandwich Islands</option><option value="sd">South Sudan</option><option value="xxr">Soviet Union (republic unidentified) [current]</option><option value="ur">Soviet Union (republic unidentified) [used before 3/1988]</option><option value="sp">Spain</option><option value="sh">Spanish North Africa</option><option value="xp">Spratly Island</option><option value="ce">Sri Lanka</option><option value="sj">Sudan</option><option value="sr">Surinam</option><option value="sq">Swaziland</option><option value="sw">Sweden</option><option value="sz">Switzerland</option><option value="sy">Syria</option><option value="ta">Tajikistan</option><option value="tz">Tanzania</option><option value="tma">Tasmania</option><option value="tnu">Tennessee</option><option value="fs">Terres australes et antarctiques fran├зaises</option><option value="txu">Texas</option><option value="th">Thailand</option><option value="em">Timor-Leste</option><option value="tg">Togo</option><option value="tl">Tokelau</option><option value="to">Tonga</option><option value="tr">Trinidad and Tobago</option><option value="ti">Tunisia</option><option value="tu">Turkey</option><option value="tk">Turkmenistan</option><option value="tc">Turks and Caicos Islands</option><option value="tv">Tuvalu</option><option value="ug">Uganda</option><option value="un">Ukraine</option><option value="ts">United Arab Emirates</option><option value="xxk">United Kingdom (country unidentified) [current]</option><option value="uk">United Kingdom (country unidentified) [used before 1988]</option><option value="uik">United Kingdom (Miscellaneous Islands)</option><option value="xxu">United States (state unidentified) [current]</option><option value="us">United States (state unidentified) [used before 1988]</option><option value="uc">United States (Miscellaneous Caribbean Islands)</option><option value="up">United States (Miscellaneous Pacific Islands)</option><option value="uy">Uruguay</option><option value="utu">Utah</option><option value="uz">Uzbekistan</option><option value="nn">Vanuatu</option><option value="vc">Vatican City</option><option value="ve">Venezuela</option><option value="vtu">Vermont</option><option value="vra">Victoria</option><option value="vm">Vietnam</option><option value="vi">Virgin Islands of the United States</option><option value="vau">Virginia</option><option value="wk">Wake Island</option><option value="wlk">Wales</option><option value="wf">Wallis and Futuna</option><option value="wau">Washington (State)</option><option value="wj">West Bank of the Jordan River</option><option value="wvu">West Virginia</option><option value="wea">Western Australia</option><option value="ss">Western Sahara</option><option value="wiu">Wisconsin</option><option value="wyu">Wyoming</option><option value="ye">Yemen</option><option value="ykc">Yukon Territory</option><option value="za">Zambia</option><option value="rh">Zimbabwe</option></select>
</div>