---
- name: Install prerequisites for Medlib
  dnf: name={{ item }} state=latest
  with_items:
    - yaz
    - libyaz5
    - libyaz5-dev
    # TODO: Check what of the following is really required.
    - gcc
    - patch
    - make
    - vim
    - wget
    - curl