---
- name: PHP | Add php-7.0 PPA
  apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes
  sudo: true

- name: PHP | install php packages
  apt: name={{ item }} state=installed
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-json
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-odbc
    - php7.0-pgsql
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xmlrpc
    - php7.0-opcache
    - php7.0-intl
    - php7.0-bz2
    - php7.0-xml

- name: Configure PHP-FPM
  copy: src=php-fpm.conf dest=/etc/php5/fpm/php-fpm.conf
  notify: restart php5-fpm

- name: Configure PHP
  template:
    src=php.ini.j2
    dest=/etc/php/7.0/fpm/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  notify: restart php7.0-fpm

- name: Configure PHP Client
  template:
    src=php.ini.j2
    dest=/etc/php/7.0/cli/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  notify: restart php7.0-fpm

- name: Add site config to PHP-FPM
  template: src=www.conf.j2 dest=/etc/php/7.0/fpm/pool.d/www.conf
  notify: restart php7.0-fpm

- name: Install Composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version={{composer_version}}"
  args:
    creates: "/usr/bin/composer"

- name: Activate MCrypt
  command: php7enmod mcrypt
  notify: restart php7.0-fpm
